### ISSUE TITLE
configmap/secret

### ISSUE THREAD

**Issue by kfox1111** [remche/zero-to-shinyproxy#5]
Since the config can contain secrets for users, it probably should be made a secret instead of a configmap.

**Comment by remche** [comment]
Since I totally agree that secrets have to be stored sensitively, I would prefer not to make the whole `application.yaml` a configmap.
I'm actually working on a clever way to build `application.yaml` (see #3 and 218cfb3)

I think we should pick sensitive values and put them in secret, exposing them to the app at runtime through env var (see https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html).

A first step could be to pick whole `proxy.auth` and use `SPRING_APPLICATION_JSON` env var.

I will do some tests after my holiday break :beach_umbrella:

**Comment by remche** [comment]
@kfox1111 feel free to test PR #7 before merge ;)
